### Section title placeholder

Description placeholder

In [ ]:
# !pip install -r requirements.txt
# !python -m spacy download de_core_news_sm

In [3]:
from warnings import filterwarnings

filterwarnings("ignore")

In [5]:
import os
import re
from typing import List, Dict
from pprint import pprint
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import spacy
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, roc_auc_score
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier

### Section title placeholder

Description placeholder

In [6]:
def get_html_text(filepath: str) -> str:
    """
    
    """
    with open(filepath, encoding='ISO-8859-1') as f:
        soup = BeautifulSoup(f.read(), "html")
    
    tags_to_decompose = [
        tag 
        for tag_name in ("style", "script")
        for tag in soup.find_all(tag_name)
    ]
    
    for tag in tags_to_decompose:
        tag.decompose()
    
    return soup.get_text(" ")

get_html_text(os.path.join("htmls", "0.html"))

'\n \n \n \n \n \n Bauchspeicheldrüse | Klinik für Allgemein-, Viszeral- und Kinderchirurgie Göttingen \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n Klinik für Allgemein-, Viszeral- und Kinderchirurgie \n zur Hauptnavigation springen \n zum Inhalt wechseln \n \n Aktuelles und Kontakt Kontakt \n \n \n Logo der Universtätsmedizin Göttingen \n \n \n \n \n \n \n \n \n \n Navigation öffnen oder schliessen \n \n \n \n \n \n \n Hauptnavigation Subnavigation öffnen oder schliessen Medizinische Versorgung Poliklinik Sonographie Schilddrüse Speiseröhre und Magen Darm Bauchspeicheldrüse CED Leber und Galle Hernien Koloproktologie Adipositaschirurgie Kinderchirurgie Sarkomchirurgie HIPEC Roboterchirurgie Interdisziplinäre Zentren Subnavigation öffnen oder schliessen Forschung Klinische Studien Tumorepigenetik AG Conradi AG Gaedcke AG Grade AG Krause AG Sperling AG Sprenger AG Wegwitz Promotion Publikationen Subnavigation öffnen oder schliessen Lehre Module Blockpraktikum Famulaturen/P

Description placeholder

In [7]:
def get_all_texts() -> Dict[int, str]:
    """
    
    """
    return {
        int(file.replace(".html", "")): get_html_text(os.path.join("htmls", file))
        for file in os.listdir("htmls")
    }

all_texts = get_all_texts()

### Section title placeholder

Description placeholder

In [8]:
train_df = pd.read_csv("train.csv")
train_df

url  doc_id  label
0   http://elbe-elster-klinikum.de/fachbereiche/ch...       1      1
1   http://klinikum-bayreuth.de/einrichtungen/zent...       3      3
2   http://klinikum-braunschweig.de/info.php/?id_o...       4      1
3   http://klinikum-braunschweig.de/info.php/?id_o...       5      1
4   http://klinikum-braunschweig.de/zuweiser/tumor...       6      3
..                                                ...     ...    ...
95   http://www.unicross.uni-freiburg.de/thema/unifm/     140      1
96  http://www.uniklinik-duesseldorf.de/patienten-...     141      1
97  http://www.vivantes.de/fuer-sie-vor-ort/klinik...     144      2
98  http://www.vivantes.de/fuer-sie-vor-ort/klinik...     145      2
99  http://www.walburga-krankenhaus.de/wk/artikel/...     146      1

[100 rows x 3 columns]

Description placeholder

In [9]:
train_df.label.value_counts()

2    59
1    32
3     9
Name: label, dtype: int64

Description placeholder

In [10]:
del train_df['url']
train_df['text'] = train_df['doc_id'].apply(lambda x: all_texts[x])
train_df

doc_id  label                                               text
0        1      1  \n \n \n \n \n \n Elbe-Elster Klinikum - Chiru...
1        3      3  \n \n \n \n \n \n \n Onkologisches Zentrum - K...
2        4      1  \n \n Zentrum - Sozialpädiatrisches Zentrum -...
3        5      1  \n \n Leistung - Spezielle Unterstützung bei ...
4        6      3  \n \n Zuweiser - Tumorkonferenzen - Tumorkonfe...
..     ...    ...                                                ...
95     140      1  \n \n \n \n \n \n \n \n \n \n \n uniFM | uniCR...
96     141      1  \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \...
97     144      2  \n \n \n \n \n \n \n \n \n \n \n \n Für Ärzt...
98     145      2  \n \n \n \n \n \n \n \n \n \n \n \n \n \n Inne...
99     146      1  \n \n \n Versorgung von Krebspatienten stärke...

[100 rows x 3 columns]

### Section title placeholder

Description placeholder

In [11]:
nlp = spacy.load("de_core_news_sm")

Description placeholder

In [12]:
def preprocessor(text: str) -> str:
    """
    Removes punctuation from text using regular expressions
    """
    text = re.sub('<[^>]*>', '', text)
    text = re.sub('[\W]+', '', text.lower())
    
    return text


def tokenize(sent: spacy.tokens.Span) -> List[str]:
    """
    Extracts a list of word lemmas from spacy's sentence object.
    Stopwords are filtered out as well as tokens representing only
    whitespace or punctuation.
    """
    lemmas = [
        preprocessor(token.lemma_)
        for token in sent
        if all([
            not token.is_stop,
            token.pos_ not in {"SPACE", "PUNCT"}
        ])
    ]
    return [lem for lem in lemmas if lem]


def tokenize_all(text: str) -> List[List[str]]:
    """
    Parses text to a list of lists. 
    Each list inside the main list represents a sentence in text.
    All tokens in the sentence are cleaned, lemmatized and filtered.
    """
    global nlp
    
    doc = nlp(text)
    
    return [
        tokenize(sent)
        for sent in doc.sents
    ]

Description placeholder

In [24]:
train_df['tokens'] = train_df['text'].apply(tokenize_all)
train_df['clean_sents'] = train_df['tokens'].apply(lambda x: [" ".join(toks) for toks in x])
train_df['clean_text'] = train_df['clean_sents'].apply(lambda x: " ".join(x))
train_df

doc_id  label                                               text  \
0        1      1  \n \n \n \n \n \n Elbe-Elster Klinikum - Chiru...   
1        3      3  \n \n \n \n \n \n \n Onkologisches Zentrum - K...   
2        4      1  \n \n Zentrum - Sozialpädiatrisches Zentrum -...   
3        5      1  \n \n Leistung - Spezielle Unterstützung bei ...   
4        6      3  \n \n Zuweiser - Tumorkonferenzen - Tumorkonfe...   
..     ...    ...                                                ...   
95     140      1  \n \n \n \n \n \n \n \n \n \n \n uniFM | uniCR...   
96     141      1  \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \...   
97     144      2  \n \n \n \n \n \n \n \n \n \n \n \n Für Ärzt...   
98     145      2  \n \n \n \n \n \n \n \n \n \n \n \n \n \n Inne...   
99     146      1  \n \n \n Versorgung von Krebspatienten stärke...   

                                          sent_tokens  \
0   [[elbeelster, klinikum, chirurgie, finsterwald...   
1   [[], [onkologisches, zentrum, klinikum, bayreu...   
2   [[], [zentrum, sozialpãdiatrisches, zentrum, s...   
3   [[], [leistung, speziell, unterstã¼tzung, anme...   
4   [[], [zuweiser, tumorkonferenzen, tumorkonfere...   
..                                                ...   
95  [[unifm, unicross, news, and, magazin, theme, ...   
96  [[], [interdisziplinãre, neurovaskulãre, konfe...   
97  [[fã¼r], [ãrzte], [vivantes, javascript, schei...   
98  [[innere, medizin, â, hãmatologie, onkologie, ...   
99  [[versorgung, krebspatienten, stãrken, st, wal...   

                                               tokens  \
0   [[elbeelster, klinikum, chirurgie, finsterwald...   
1   [[], [onkologisches, zentrum, klinikum, bayreu...   
2   [[], [zentrum, sozialpãdiatrisches, zentrum, s...   
3   [[], [leistung, speziell, unterstã¼tzung, anme...   
4   [[], [zuweiser, tumorkonferenzen, tumorkonfere...   
..                                                ...   
95  [[unifm, unicross, news, and, magazin, theme, ...   
96  [[], [interdisziplinãre, neurovaskulãre, konfe...   
97  [[fã¼r], [ãrzte], [vivantes, javascript, schei...   
98  [[innere, medizin, â, hãmatologie, onkologie, ...   
99  [[versorgung, krebspatienten, stãrken, st, wal...   

                                          clean_sents  \
0   [elbeelster klinikum chirurgie finsterwalde su...   
1   [, onkologisches zentrum klinikum bayreuth, ak...   
2   [, zentrum sozialpãdiatrisches zentrum stãdtis...   
3   [, leistung speziell unterstã¼tzung anmeldung ...   
4   [, zuweiser tumorkonferenzen tumorkonferenz ga...   
..                                                ...   
95  [unifm unicross news and magazin theme home, k...   
96  [, interdisziplinãre neurovaskulãre konferenz ...   
97  [fã¼r, ãrzte, vivantes javascript scheinen bro...   
98  [innere medizin â hãmatologie onkologie pallia...   
99  [versorgung krebspatienten stãrken st walburga...   

                                           clean_text  \
0   elbeelster klinikum chirurgie finsterwalde suc...   
1    onkologisches zentrum klinikum bayreuth aktue...   
2    zentrum sozialpãdiatrisches zentrum stãdtisch...   
3    leistung speziell unterstã¼tzung anmeldung ge...   
4    zuweiser tumorkonferenzen tumorkonferenz gast...   
..                                                ...   
95  unifm unicross news and magazin theme home kon...   
96   interdisziplinãre neurovaskulãre konferenz ǀ ...   
97  fã¼r ãrzte vivantes javascript scheinen browse...   
98  innere medizin â hãmatologie onkologie palliat...   
99  versorgung krebspatienten stãrken st walburgak...   

                                              vectors  
0   [-0.3885404, 0.44329208, 1.1765691, 0.18398188...  
1   [-0.05751672, 0.639646, 1.3166927, 0.35740948,...  
2   [-0.28596362, 0.20628653, 0.94600266, 0.221883...  
3   [-0.33647257, 0.20716135, 1.0760807, 0.3270652...  
4   [-0.30618563, 0.48690826, 1.2848387, 0.2830735...  
..                                                ...  
95  [-0

### Section title placeholder

Description placeholder

In [25]:
train_df['vectors'] = train_df['clean_text'].apply(lambda x: nlp(x).vector)
train_df

doc_id  label                                               text  \
0        1      1  \n \n \n \n \n \n Elbe-Elster Klinikum - Chiru...   
1        3      3  \n \n \n \n \n \n \n Onkologisches Zentrum - K...   
2        4      1  \n \n Zentrum - Sozialpädiatrisches Zentrum -...   
3        5      1  \n \n Leistung - Spezielle Unterstützung bei ...   
4        6      3  \n \n Zuweiser - Tumorkonferenzen - Tumorkonfe...   
..     ...    ...                                                ...   
95     140      1  \n \n \n \n \n \n \n \n \n \n \n uniFM | uniCR...   
96     141      1  \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \...   
97     144      2  \n \n \n \n \n \n \n \n \n \n \n \n Für Ärzt...   
98     145      2  \n \n \n \n \n \n \n \n \n \n \n \n \n \n Inne...   
99     146      1  \n \n \n Versorgung von Krebspatienten stärke...   

                                          sent_tokens  \
0   [[elbeelster, klinikum, chirurgie, finsterwald...   
1   [[], [onkologisches, zentrum, klinikum, bayreu...   
2   [[], [zentrum, sozialpãdiatrisches, zentrum, s...   
3   [[], [leistung, speziell, unterstã¼tzung, anme...   
4   [[], [zuweiser, tumorkonferenzen, tumorkonfere...   
..                                                ...   
95  [[unifm, unicross, news, and, magazin, theme, ...   
96  [[], [interdisziplinãre, neurovaskulãre, konfe...   
97  [[fã¼r], [ãrzte], [vivantes, javascript, schei...   
98  [[innere, medizin, â, hãmatologie, onkologie, ...   
99  [[versorgung, krebspatienten, stãrken, st, wal...   

                                               tokens  \
0   [[elbeelster, klinikum, chirurgie, finsterwald...   
1   [[], [onkologisches, zentrum, klinikum, bayreu...   
2   [[], [zentrum, sozialpãdiatrisches, zentrum, s...   
3   [[], [leistung, speziell, unterstã¼tzung, anme...   
4   [[], [zuweiser, tumorkonferenzen, tumorkonfere...   
..                                                ...   
95  [[unifm, unicross, news, and, magazin, theme, ...   
96  [[], [interdisziplinãre, neurovaskulãre, konfe...   
97  [[fã¼r], [ãrzte], [vivantes, javascript, schei...   
98  [[innere, medizin, â, hãmatologie, onkologie, ...   
99  [[versorgung, krebspatienten, stãrken, st, wal...   

                                          clean_sents  \
0   [elbeelster klinikum chirurgie finsterwalde su...   
1   [, onkologisches zentrum klinikum bayreuth, ak...   
2   [, zentrum sozialpãdiatrisches zentrum stãdtis...   
3   [, leistung speziell unterstã¼tzung anmeldung ...   
4   [, zuweiser tumorkonferenzen tumorkonferenz ga...   
..                                                ...   
95  [unifm unicross news and magazin theme home, k...   
96  [, interdisziplinãre neurovaskulãre konferenz ...   
97  [fã¼r, ãrzte, vivantes javascript scheinen bro...   
98  [innere medizin â hãmatologie onkologie pallia...   
99  [versorgung krebspatienten stãrken st walburga...   

                                           clean_text  \
0   elbeelster klinikum chirurgie finsterwalde suc...   
1    onkologisches zentrum klinikum bayreuth aktue...   
2    zentrum sozialpãdiatrisches zentrum stãdtisch...   
3    leistung speziell unterstã¼tzung anmeldung ge...   
4    zuweiser tumorkonferenzen tumorkonferenz gast...   
..                                                ...   
95  unifm unicross news and magazin theme home kon...   
96   interdisziplinãre neurovaskulãre konferenz ǀ ...   
97  fã¼r ãrzte vivantes javascript scheinen browse...   
98  innere medizin â hãmatologie onkologie palliat...   
99  versorgung krebspatienten stãrken st walburgak...   

                                              vectors  
0   [-0.3885404, 0.44329208, 1.1765691, 0.18398188...  
1   [-0.05751672, 0.639646, 1.3166927, 0.35740948,...  
2   [-0.28596362, 0.20628653, 0.94600266, 0.221883...  
3   [-0.33647257, 0.20716135, 1.0760807, 0.3270652...  
4   [-0.30618563, 0.48690826, 1.2848387, 0.2830735...  
..                                                ...  
95  [-0

Description placeholder

In [26]:
class_3_oversample = train_df[train_df.label == 3].sample(20, replace=True)
oversampled_train_df = pd.concat([train_df[train_df.label != 3], class_3_oversample])
oversampled_train_df.label.value_counts()

2    59
1    32
3    20
Name: label, dtype: int64

In [27]:
x, y = np.stack(oversampled_train_df.vectors), oversampled_train_df.label.to_numpy()

X_train, x_val, Y_train, y_val = train_test_split(x, y, train_size=0.9, shuffle=True, random_state=1, stratify=y)

In [28]:
def eval_model(model, x_test, y_test):
    y_pred = model.predict(x_test)
    
    acc = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    
    
    print(f'Accuracy {acc}\n')
    print(conf_matrix)
    print()
    print(report)

In [53]:
lgr = LogisticRegression(n_jobs=5, C=1, class_weight="balanced")
lgr.fit(X_train, Y_train)

eval_model(lgr, x_val, y_val)

Accuracy 0.8333333333333334

[[3 1 0]
 [1 5 0]
 [0 0 2]]

              precision    recall  f1-score   support

           1       0.75      0.75      0.75         4
           2       0.83      0.83      0.83         6
           3       1.00      1.00      1.00         2

   micro avg       0.83      0.83      0.83        12
   macro avg       0.86      0.86      0.86        12
weighted avg       0.83      0.83      0.83        12



In [45]:
sgd = SGDClassifier(penalty='l2', alpha=1e-3, random_state=0, max_iter=10000)
sgd.fit(X_train, Y_train)

eval_model(sgd, x_val, y_val)

Accuracy 0.8333333333333334

[[4 0 0]
 [2 4 0]
 [0 0 2]]

              precision    recall  f1-score   support

           1       0.67      1.00      0.80         4
           2       1.00      0.67      0.80         6
           3       1.00      1.00      1.00         2

   micro avg       0.83      0.83      0.83        12
   macro avg       0.89      0.89      0.87        12
weighted avg       0.89      0.83      0.83        12



In [46]:
Y_train_bin = np.array([2 if l == 3 else l for l in Y_train])
y_val_bin = np.array([2 if l == 3 else l for l in y_val])

In [47]:
sgd_bin = SGDClassifier(penalty='l2', alpha=1e-3, random_state=0, max_iter=10000, tol=None)
sgd_bin.fit(X_train, Y_train_bin)

eval_model(sgd_bin, x_val, y_val_bin)

Accuracy 0.8333333333333334

[[4 0]
 [2 6]]

              precision    recall  f1-score   support

           1       0.67      1.00      0.80         4
           2       1.00      0.75      0.86         8

   micro avg       0.83      0.83      0.83        12
   macro avg       0.83      0.88      0.83        12
weighted avg       0.89      0.83      0.84        12



In [22]:
kw2tt = pd.read_csv("keyword2tumor_type.csv")
kw2tt

keyword                tumor_type
0                senologische                     Brust
1                brustzentrum                     Brust
2                      breast                     Brust
3                      thorax                     Brust
4                   thorakale                     Brust
..                        ...                       ...
121           kinderonkologie              Pädiatrische
122              pädiatrische              Pädiatrische
123               schwerpunkt               Schwerpunkt
124  stammzelltransplantation  Stammzelltransplantation
125               chirurgisch                  Surgical

[126 rows x 2 columns]

In [83]:
from collections import Counter, defaultdict

In [95]:
def detect_type(tokens):
    global kw2tt
    
    flat_tokens = [t for toks in tokens for t in toks]
    keywords = set(flat_tokens).intersection(set(kw2tt.keyword))
    word_counts = Counter(flat_tokens)
    type_map = dict(zip(kw2tt.keyword, kw2tt.tumor_type))
    
    type_counts = defaultdict(int)
    for kw in keywords:
        type_ = type_map[kw]
        type_counts[type_] += word_counts[kw]
    
    most_freq_type, _ = max(type_counts.items(), key=lambda x: x[1])
    
    return most_freq_type

In [97]:
train_df_23 = train_df[train_df.label.apply(lambda x: x in {2, 3})]

train_df_23['tumor_type'] = train_df_23['tokens'].apply(detect_type)
train_df_23

doc_id  label                                               text  \
1        3      3  \n \n \n \n \n \n \n Onkologisches Zentrum - K...   
4        6      3  \n \n Zuweiser - Tumorkonferenzen - Tumorkonfe...   
10      13      2  \n \n \n Krebszentrum Reutlingen: Zentrale Ein...   
11      14      2  \n \n \n \n \n Leistungsspektrum: Sankt Marien...   
12      17      2  \n \n \n \n \n Minimal-invasive Chirurgie: San...   
..     ...    ...                                                ...   
89     132      2  \n \n \n \n \n Thorax Klinik: Lungenkrebszentr...   
90     133      2  \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n A...   
91     136      2  \n \n \n \n \n \n \n \n Veranstaltungen: UKM -...   
97     144      2  \n \n \n \n \n \n \n \n \n \n \n \n Für Ärzt...   
98     145      2  \n \n \n \n \n \n \n \n \n \n \n \n \n \n Inne...   

                                               tokens  \
1   [[], [onkologisches, zentrum, klinikum, bayreu...   
4   [[], [zuweiser, tumorkonferenzen, tumorkonfere...   
10  [[], [krebszentrum, reutlingen, zentrale, einr...   
11  [[], [leistungsspektrum], [sankt, marienhospit...   
12  [[minimalinvasive, chirurgie], [sankt, marienh...   
..                                                ...   
89  [[thorax, klinik, lungenkrebszentrum, nct, hei...   
90  [[], [ambulanz, sprechstundenund, kontakt, uni...   
91  [[], [veranstaltung, ukm, hautklinik], [suche,...   
97  [[fã¼r], [ãrzte], [vivantes, javascript, schei...   
98  [[innere, medizin, â, hãmatologie, onkologie, ...   

                                          clean_sents  \
1   [, onkologisches zentrum klinikum bayreuth, ak...   
4   [, zuweiser tumorkonferenzen tumorkonferenz ga...   
10  [, krebszentrum reutlingen zentrale einrichtun...   
11  [, leistungsspektrum, sankt marienhospital bue...   
12  [minimalinvasive chirurgie, sankt marienhospit...   
..                                                ...   
89  [thorax klinik lungenkrebszentrum nct heidelbe...   
90  [, ambulanz sprechstundenund kontakt universit...   
91  [, veranstaltung ukm hautklinik, suche suche h...   
97  [fã¼r, ãrzte, vivantes javascript scheinen bro...   
98  [innere medizin â hãmatologie onkologie pallia...   

                                           clean_text  \
1    onkologisches zentrum klinikum bayreuth aktue...   
4    zuweiser tumorkonferenzen tumorkonferenz gast...   
10   krebszentrum reutlingen zentrale einrichtung ...   
11   leistungsspektrum sankt marienhospital buer g...   
12  minimalinvasive chirurgie sankt marienhospital...   
..                                                ...   
89  thorax klinik lungenkrebszentrum nct heidelber...   
90   ambulanz sprechstundenund kontakt universitãt...   
91   veranstaltung ukm hautklinik suche suche haut...   
97  fã¼r ãrzte vivantes javascript scheinen browse...   
98  innere medizin â hãmatologie onkologie palliat...   

                                              vectors        tumor_type  
1   [-0.05751672, 0.639646, 1.3166927, 0.35740948,...             Brust  
4   [-0.30618563, 0.48690826, 1.2848387, 0.2830735...             Magen  
10  [0.084352665, 0.26025638, 1.3280164, 0.2644429...  Interdisziplinär  
11  [-0.57697684, 0.012666922, 1.0382532, 0.446892...              Darm  
12  [-0.641403, 0.026014825, 1.0859053, 0.44600007...              Darm  
..                                                ...               ...  
89  [-0.42971414, -0.065575615, 0.7600092, 0.37320...             Lunge  
90  [-0.6437655, 0.15264697, 1.2336291, 0.27001214...       Schwerpunkt  
91  [-0.21947816, 0.9361462, 1.2044301, 0.11974818...              Haut  
97  [-0.5012306, 0.24726734, 1.4206642, 0.10274181...       Schwerpunkt  
98  [-0.50758284, 0.15702526, 1.3736418, 0.1842688...       Schwerpunkt  

[68 rows x 8 columns]

In [113]:
weekdays = {'sonntag', 'montag', 'dienstag', 'mittwoch', 'donnerstag', 'freitag', 'samstag'}

def detect_weekday(tokens):
    flat_tokens = [t for toks in tokens for t in toks]
    found_weekdays = set(flat_tokens).intersection(weekdays)
    word_counts = Counter(flat_tokens)
    
    weekday_counts = defaultdict(int)
    for wd in found_weekdays:
        weekday_counts[wd] += word_counts[wd]
    
    if not weekday_counts:
        return None
    
    most_freq_wd, _ = max(weekday_counts.items(), key=lambda x: x[1])
    
    return most_freq_wd

In [114]:
train_df_23['weekday'] = train_df_23['tokens'].apply(detect_weekday)
train_df_23

doc_id  label                                               text  \
1        3      3  \n \n \n \n \n \n \n Onkologisches Zentrum - K...   
4        6      3  \n \n Zuweiser - Tumorkonferenzen - Tumorkonfe...   
10      13      2  \n \n \n Krebszentrum Reutlingen: Zentrale Ein...   
11      14      2  \n \n \n \n \n Leistungsspektrum: Sankt Marien...   
12      17      2  \n \n \n \n \n Minimal-invasive Chirurgie: San...   
..     ...    ...                                                ...   
89     132      2  \n \n \n \n \n Thorax Klinik: Lungenkrebszentr...   
90     133      2  \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n A...   
91     136      2  \n \n \n \n \n \n \n \n Veranstaltungen: UKM -...   
97     144      2  \n \n \n \n \n \n \n \n \n \n \n \n Für Ärzt...   
98     145      2  \n \n \n \n \n \n \n \n \n \n \n \n \n \n Inne...   

                                               tokens  \
1   [[], [onkologisches, zentrum, klinikum, bayreu...   
4   [[], [zuweiser, tumorkonferenzen, tumorkonfere...   
10  [[], [krebszentrum, reutlingen, zentrale, einr...   
11  [[], [leistungsspektrum], [sankt, marienhospit...   
12  [[minimalinvasive, chirurgie], [sankt, marienh...   
..                                                ...   
89  [[thorax, klinik, lungenkrebszentrum, nct, hei...   
90  [[], [ambulanz, sprechstundenund, kontakt, uni...   
91  [[], [veranstaltung, ukm, hautklinik], [suche,...   
97  [[fã¼r], [ãrzte], [vivantes, javascript, schei...   
98  [[innere, medizin, â, hãmatologie, onkologie, ...   

                                          clean_sents  \
1   [, onkologisches zentrum klinikum bayreuth, ak...   
4   [, zuweiser tumorkonferenzen tumorkonferenz ga...   
10  [, krebszentrum reutlingen zentrale einrichtun...   
11  [, leistungsspektrum, sankt marienhospital bue...   
12  [minimalinvasive chirurgie, sankt marienhospit...   
..                                                ...   
89  [thorax klinik lungenkrebszentrum nct heidelbe...   
90  [, ambulanz sprechstundenund kontakt universit...   
91  [, veranstaltung ukm hautklinik, suche suche h...   
97  [fã¼r, ãrzte, vivantes javascript scheinen bro...   
98  [innere medizin â hãmatologie onkologie pallia...   

                                           clean_text  \
1    onkologisches zentrum klinikum bayreuth aktue...   
4    zuweiser tumorkonferenzen tumorkonferenz gast...   
10   krebszentrum reutlingen zentrale einrichtung ...   
11   leistungsspektrum sankt marienhospital buer g...   
12  minimalinvasive chirurgie sankt marienhospital...   
..                                                ...   
89  thorax klinik lungenkrebszentrum nct heidelber...   
90   ambulanz sprechstundenund kontakt universitãt...   
91   veranstaltung ukm hautklinik suche suche haut...   
97  fã¼r ãrzte vivantes javascript scheinen browse...   
98  innere medizin â hãmatologie onkologie palliat...   

                                              vectors        tumor_type  \
1   [-0.05751672, 0.639646, 1.3166927, 0.35740948,...             Brust   
4   [-0.30618563, 0.48690826, 1.2848387, 0.2830735...             Magen   
10  [0.084352665, 0.26025638, 1.3280164, 0.2644429...  Interdisziplinär   
11  [-0.57697684, 0.012666922, 1.0382532, 0.446892...              Darm   
12  [-0.641403, 0.026014825, 1.0859053, 0.44600007...              Darm   
..                                                ...               ...   
89  [-0.42971414, -0.065575615, 0.7600092, 0.37320...             Lunge   
90  [-0.6437655, 0.15264697, 1.2336291, 0.27001214...       Schwerpunkt   
91  [-0.21947816, 0.9361462, 1.2044301, 0.11974818...              Haut   
97  [-0.5012306, 0.24726734, 1.4206642, 0.10274181...       Schwerpunkt   
98  [-0.50758284, 0.15702526, 1.3736418, 0.1842688...       Schwerpunkt   

       weekday  
1   donnerstag  
4     dienstag  
10        None  
11        None  
12        None  
..         ...  
89        None  
90        None  
91    mittwoch  
97  donnersta

In [118]:
train_df_23[~train_df_23.weekday.isna()].shape

(17, 9)